language: cpp
compiler:
  - clang
  - gcc
os:
  - linux
before_install:
  - sudo apt-get -y install ninja-build
script:
  - cmake --log-level=VERBOSE -G "Ninja Multi-Config" -B build; ninja -j12 -C build
branches:
  only:
    - main
