version: 2.1
executors:
  clang:
    docker:
      - image: 'cimg/base:2020.01'
    environment:
      CC: clang
      CXX: clang++
  gcc:
    environment:
      CC: gcc-10
      CXX: g++-10
jobs:
  build:
    parameters:
      compiler:
        type: executor
      variant:
        type: string
    executor: << parameters.compiler >>
    steps:
      - checkout
      - run:
          name: cmake
          environment:
            CMAKE_BUILD_TYPE: << parameters.variant >>
          command: cmake -G "Ninja Multi-Config" -B build
      - run:
          name: ninja
          command: ninja -j12 -C build
workflows:
  all-tests:
    jobs:
      - build:
          matrix:
            parameters:
              compiler:
                - gcc
                - clang
              variant:
                - Debug
